language: node_js
sudo: false
node_js:
  - 10
  - 8
  - 6
notifications:
  email:
    on_success: "never"
script:
  - "npm run lint"
  - "./bin/run-in-package npm i"
  - "./bin/link"
  - "./bin/run-in-package npm run travis-test"
  - "npm run combine-coverage"
  - "npm run coveralls"
